// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ghhvmlwonbsqurewzwhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoaHZtbHdvbmJzcXVyZXd6d2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1NTYwMDgsImV4cCI6MjA4MzEzMjAwOH0.4gKmMEhJXc2AaFlGXYzdbMI0TDWfsJFFizfWi76KoU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);